"""
Helper file with python dictionary of all nfl conferences/divisions
"""

divisions = {
    "Arizona Cardinals": "NFC West",
    "Atlanta Falcons": "NFC South",
    "Baltimore Ravens": "AFC North",
    "Buffalo Bills": "AFC East",
    "Carolina Panthers": "NFC South",
    "Chicago Bears": "NFC North",
    "Cincinnati Bengals": "AFC North",
    "Cleveland Browns": "AFC North",
    "Dallas Cowboys": "NFC East",
    "Denver Broncos": "AFC West",
    "Detroit Lions": "NFC North",
    "Green Bay Packers": "NFC North",
    "Houston Texans": "AFC South",
    "Indianapolis Colts": "AFC South",
    "Jacksonville Jaguars": "AFC South",
    "Kansas City Chiefs": "AFC West",
    "Las Vegas Raiders": "AFC West",
    "Los Angeles Chargers": "AFC West",
    "Los Angeles Rams": "NFC West",
    "Miami Dolphins": "AFC East",
    "Minnesota Vikings": "NFC North",
    "New England Patriots": "AFC East",
    "New Orleans Saints": "NFC South",
    "New York Giants": "NFC East",
    "New York Jets": "AFC East",
    "Oakland Raiders": "AFC West",
    "Philadelphia Eagles": "NFC East",
    "Pittsburgh Steelers": "AFC North",
    "San Diego Chargers": "AFC West",
    "San Francisco 49ers": "NFC West",
    "Seattle Seahawks": "NFC West",
    "St. Louis Rams": "NFC West",
    "Tampa Bay Buccaneers": "NFC South",
    "Tennessee Titans": "AFC South",
    "Washington Redskins": "NFC East",
    "Washington Football Team": "NFC East",
    "Washington Commanders": "NFC East"
}

division_ids = {
    "AFC East": 0,
    "AFC West": 1,
    "AFC North": 2,
    "AFC South": 3,
    "NFC East": 4,
    "NFC West": 5,
    "NFC North": 6,
    "NFC South": 7
}

teams = {
    "Arizona Cardinals": 0,
    "ARI": 0,
    "Atlanta Falcons": 1,
    "ATL": 1,
    "Baltimore Ravens": 2,
    "BAL": 2,
    "Buffalo Bills": 3,
    "BUF": 3,
    "Carolina Panthers": 4,
    "CAR": 4,
    "Chicago Bears": 5,
    "CHI": 5,
    "Cincinnati Bengals": 6,
    "CIN": 6,
    "Cleveland Browns": 7,
    "CLE": 7,
    "Dallas Cowboys": 8,
    "DAL": 8,
    "Denver Broncos": 9,
    "DEN": 9,
    "Detroit Lions": 10,
    "DET": 10,
    "Green Bay Packers": 11,
    "GB": 11,
    "Houston Texans": 12,
    "HOU": 12,
    "Indianapolis Colts": 13,
    "IND": 13,
    "Jacksonville Jaguars": 14,
    "JAX": 14,
    "Kansas City Chiefs": 15,
    "KC": 15,
    "Las Vegas Raiders": 16,
    "LVR": 16,
    "Los Angeles Chargers": 17,
    "LAC": 17,
    "Los Angeles Rams": 18,
    "LAR": 18,
    "Miami Dolphins": 19,
    "MIA": 19,
    "Minnesota Vikings": 20,
    "MIN": 20,
    "New England Patriots": 21,
    "NE": 21,
    "New Orleans Saints": 22,
    "NO": 22,
    "New York Giants": 23,
    "NYG": 23,
    "New York Jets": 24,
    "NYJ": 24,
    "Oakland Raiders": 16,
    "OAK": 16,
    "Philadelphia Eagles": 25,
    "PHI": 25,
    "Pittsburgh Steelers": 26,
    "PIT": 26,
    "San Diego Chargers": 17,
    "SD": 27,
    "San Francisco 49ers": 27,
    "SF": 28,
    "Seattle Seahawks": 28,
    "SEA": 29,
    "St. Louis Rams": 18,
    "STL": 18,
    "Tampa Bay Buccaneers": 29,
    "TB": 29,
    "Tennessee Titans": 30,
    "TEN": 30,
    "Washington Redskins": 31,
    "WAS": 31,
    "Washington Football Team": 31,
    "Washington Commanders": 31,
    "PICK": -1
}

team_abbreviations = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Oakland Raiders": "OAK",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Diego Chargers": "SD",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "St. Louis Rams": "STL",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Redskins": "WAS",
    "Washington Football Team": "WAS",
    "Washington Commanders": "WAS",
}

team_markets = {
    "Arizona Cardinals": "Arizona",
    "Atlanta Falcons": "Atlanta",
    "Baltimore Ravens": "Baltimore",
    "Buffalo Bills": "Buffalo",
    "Carolina Panthers": "Carolina",
    "Chicago Bears": "Chicago",
    "Cincinnati Bengals": "Cincinnati",
    "Cleveland Browns": "Cleveland",
    "Dallas Cowboys": "Dallas",
    "Denver Broncos": "Denver",
    "Detroit Lions": "Detroit",
    "Green Bay Packers": "Green Bay",
    "Houston Texans": "Houston",
    "Indianapolis Colts": "Indianapolis",
    "Jacksonville Jaguars": "Jacksonville",
    "Kansas City Chiefs": "Kansas City",
    "Las Vegas Raiders": "Las Vegas",
    "Los Angeles Chargers": "LA Chargers",
    "Los Angeles Rams": "LA Rams",
    "Miami Dolphins": "Miami",
    "Minnesota Vikings": "Minnesota",
    "New England Patriots": "New England",
    "New Orleans Saints": "New Orleans",
    "New York Giants": "NY Giants",
    "New York Jets": "NY Jets",
    "Philadelphia Eagles": "Philadelphia",
    "Pittsburgh Steelers": "Pittsburgh",
    "San Francisco 49ers": "San Francisco",
    "Seattle Seahawks": "Seatle",
    "Tampa Bay Buccaneers": "Tampa Bay",
    "Tennessee Titans": "Tennessee",
    "Washington Redskins": "Washington"
}